export interface CatalogCategoryDef {
  slug: string;
  name: string;
  description: string;
  icon: string;
  displayOrder: number;
}

export interface CatalogUtilityDef {
  slug: string;
  name: string;
  description: string;
  categorySlug: string;
  implementationMode: 'LOCAL' | 'SERVER' | 'AI';
  status: 'ACTIVE' | 'DRAFT' | 'DISABLED' | 'ARCHIVED';
  isFeatured: boolean;
  displayOrder: number;
  seoTitle: string;
  seoDescription: string;
  faqContent: Array<{ question: string; answer: string }>;
  relatedSlugs: string[];
}

export const DEFAULT_CATALOG_CATEGORIES: CatalogCategoryDef[] = [
  { slug: 'image', name: 'Image Tools', description: 'Convert, compress, and resize images', icon: 'image', displayOrder: 1 },
  { slug: 'pdf', name: 'PDF Tools', description: 'Compress, merge, and convert PDF documents', icon: 'file-text', displayOrder: 2 },
  { slug: 'text', name: 'Text Tools', description: 'Format, count, and manipulate text strings', icon: 'type', displayOrder: 3 },
  { slug: 'developer', name: 'Developer Tools', description: 'Formatters, validators, and developer utilities', icon: 'code', displayOrder: 4 },
  { slug: 'ai', name: 'AI Utilities', description: 'AI-assisted writing, summarizing, and humanizing', icon: 'sparkles', displayOrder: 5 },
  { slug: 'video', name: 'Video Tools', description: 'Compress, convert, and trim videos', icon: 'video', displayOrder: 6 },
  { slug: 'audio', name: 'Audio Tools', description: 'Extract, convert, and cut audio tracks', icon: 'music', displayOrder: 7 },
  { slug: 'qr-barcode', name: 'QR & Barcode', description: 'Generate and scan QR codes and barcodes', icon: 'qr-code', displayOrder: 8 },
];

export const DEFAULT_CATALOG_UTILITIES: CatalogUtilityDef[] = [
  // Developer
  {
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format, prettify, and validate JSON data instantly in your browser.',
    categorySlug: 'developer',
    implementationMode: 'LOCAL',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 1,
    seoTitle: 'Free Online JSON Formatter & Validator',
    seoDescription: 'Format, validate, and beautify your JSON data with instant syntax highlighting.',
    faqContent: [{ question: 'Is my JSON data sent to any server?', answer: 'No, all JSON formatting occurs locally in your browser for 100% data privacy.' }],
    relatedSlugs: ['word-counter', 'text-hash'],
  },
  {
    slug: 'text-hash',
    name: 'Cryptographic Text Hash Generator',
    description: 'Generate secure SHA-256 and SHA-512 cryptographic hashes.',
    categorySlug: 'developer',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: false,
    displayOrder: 2,
    seoTitle: 'Online SHA-256 and SHA-512 Hash Generator',
    seoDescription: 'Generate secure SHA-256 cryptographic hashes for text strings.',
    faqContent: [{ question: 'Which hash algorithms are supported?', answer: 'We currently support SHA-256 and SHA-512 algorithms.' }],
    relatedSlugs: ['json-formatter'],
  },
  // Text
  {
    slug: 'word-counter',
    name: 'Word & Character Counter',
    description: 'Accurately count words, characters, sentences, and estimated reading time.',
    categorySlug: 'text',
    implementationMode: 'LOCAL',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 3,
    seoTitle: 'Free Online Word & Character Counter',
    seoDescription: 'Real-time word and character counter tool with reading time estimation.',
    faqContent: [{ question: 'Does this tool count spaces?', answer: 'The counter provides separate metrics for characters with spaces and without spaces.' }],
    relatedSlugs: ['text-cleaner', 'case-converter'],
  },
  {
    slug: 'text-cleaner',
    name: 'Text Cleaner',
    description: 'Clean up messy text by normalizing whitespace, stripping excess blank lines, and fixing line endings.',
    categorySlug: 'text',
    implementationMode: 'LOCAL',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 4,
    seoTitle: 'Free Online Text Cleaner - Remove Whitespace & Extra Lines',
    seoDescription: 'Instantly clean up and normalize unformatted or copied text strings.',
    faqContent: [{ question: 'Does this tool send my text anywhere?', answer: 'No, text cleaning executes entirely in your browser.' }],
    relatedSlugs: ['case-converter', 'word-counter'],
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    description: 'Transform text case between UPPERCASE, lowercase, Title Case, Sentence case, camelCase, snake_case, and kebab-case.',
    categorySlug: 'text',
    implementationMode: 'LOCAL',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 5,
    seoTitle: 'Online Case Converter - UPPERCASE, lowercase, Title Case',
    seoDescription: 'Easily switch text casing between uppercase, lowercase, sentence case, title case, and code formats.',
    faqContent: [{ question: 'Which programming cases are supported?', answer: 'We support camelCase, snake_case, and kebab-case.' }],
    relatedSlugs: ['text-cleaner', 'word-counter'],
  },
  // AI
  {
    slug: 'ai-summarizer',
    name: 'AI Text Summarizer',
    description: 'Summarize long articles, reports, and essays into clear key takeaways.',
    categorySlug: 'ai',
    implementationMode: 'AI',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 6,
    seoTitle: 'Free AI Text Summarizer Tool',
    seoDescription: 'Summarize long texts, essays, and articles with advanced generative AI.',
    faqContent: [{ question: 'How long can the input text be?', answer: 'You can submit up to 100KB of text per summary request.' }],
    relatedSlugs: ['ai-humanizer', 'ai-paraphraser'],
  },
  {
    slug: 'ai-humanizer',
    name: 'AI Humanizer',
    description: 'Refine and improve AI-assisted text to read naturally with fluent human rhythm and phrasing.',
    categorySlug: 'ai',
    implementationMode: 'AI',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 7,
    seoTitle: 'Free AI Humanizer - Improve Writing Naturalness & Flow',
    seoDescription: 'Refine drafts to sound more natural, expressive, and engaging with AI-guided phrasing.',
    faqContent: [{ question: 'Does this improve readability?', answer: 'Yes, it enhances rhythm, natural cadence, and vocabulary variety.' }],
    relatedSlugs: ['ai-paraphraser', 'ai-grammar-checker'],
  },
  {
    slug: 'ai-paraphraser',
    name: 'AI Paraphraser',
    description: 'Rephrase sentences and rewrite paragraphs clearly while preserving essential meaning.',
    categorySlug: 'ai',
    implementationMode: 'AI',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 8,
    seoTitle: 'Free AI Paraphraser Tool - Rewrite & Rephrase Text',
    seoDescription: 'Paraphrase any text in standard, fluent, creative, or concise writing styles.',
    faqContent: [{ question: 'How much text can I paraphrase?', answer: 'Up to 50,000 characters per request.' }],
    relatedSlugs: ['ai-humanizer', 'ai-grammar-checker'],
  },
  {
    slug: 'ai-grammar-checker',
    name: 'AI Grammar Checker',
    description: 'Find and fix grammatical mistakes, punctuation errors, spelling typos, and stylistic awkwardness.',
    categorySlug: 'ai',
    implementationMode: 'AI',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 9,
    seoTitle: 'Free AI Grammar Checker - Correct Spelling & Grammar Errors',
    seoDescription: 'Accurately detect and fix grammar, spelling, and punctuation issues with detailed explanations.',
    faqContent: [{ question: 'Does it explain mistakes?', answer: 'Yes, each issue includes recommended correction and explanation.' }],
    relatedSlugs: ['ai-humanizer', 'ai-paraphraser'],
  },
  // Image (MVP + Phase 27)
  {
    slug: 'jpg-to-png',
    name: 'JPG to PNG Converter',
    description: 'Convert JPG and JPEG images to lossless PNG format with transparent alpha support.',
    categorySlug: 'image',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 10,
    seoTitle: 'Free JPG to PNG Converter Online - Lossless Quality',
    seoDescription: 'Convert JPG images to high quality PNG format instantly in your browser.',
    faqContent: [{ question: 'Is the conversion lossless?', answer: 'Yes, it preserves all pixel detail directly in PNG format.' }],
    relatedSlugs: ['png-to-jpg', 'image-compressor'],
  },
  {
    slug: 'png-to-jpg',
    name: 'PNG to JPG Converter',
    description: 'Convert PNG images to compact JPEG format with configurable quality and deterministic background compositing.',
    categorySlug: 'image',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 11,
    seoTitle: 'Free PNG to JPG Converter Online - Fast & Secure',
    seoDescription: 'Convert transparent or standard PNG images to standard JPEG format.',
    faqContent: [{ question: 'How are transparent backgrounds handled?', answer: 'Transparent pixels are smoothly blended over a clean white background.' }],
    relatedSlugs: ['jpg-to-png', 'image-compressor'],
  },
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress JPG and PNG images to reduce file size with optimal visual quality.',
    categorySlug: 'image',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 12,
    seoTitle: 'Free Online Image Compressor - Compress JPG & PNG Files',
    seoDescription: 'Reduce image file sizes by up to 80% without noticeable quality degradation.',
    faqContent: [{ question: 'Which formats are supported?', answer: 'JPG, JPEG, and PNG images up to 15MB.' }],
    relatedSlugs: ['jpg-to-png', 'image-resizer'],
  },
  {
    slug: 'image-to-pdf',
    name: 'Image to PDF Converter',
    description: 'Convert single or multiple JPG and PNG images into a clean, combined PDF document with custom margins and orientations.',
    categorySlug: 'image',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 13,
    seoTitle: 'Free Image to PDF Converter Online - JPG & PNG to PDF',
    seoDescription: 'Convert and merge JPG and PNG photos into a single high-quality PDF document instantly.',
    faqContent: [{ question: 'Can I combine multiple images into one PDF?', answer: 'Yes, upload and order multiple images into a single PDF.' }],
    relatedSlugs: ['jpg-to-png', 'pdf-merge'],
  },
  {
    slug: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize JPG, PNG, and WebP images by exact pixel dimensions or percentage while preserving crisp aspect ratios.',
    categorySlug: 'image',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 14,
    seoTitle: 'Free Online Image Resizer - Resize JPG, PNG & WebP',
    seoDescription: 'Quickly resize images to exact dimensions or percentage scale with high fidelity.',
    faqContent: [{ question: 'Does resizing reduce quality?', answer: 'Our resizer uses advanced interpolation to preserve sharpness.' }],
    relatedSlugs: ['image-compressor', 'image-cropper'],
  },
  {
    slug: 'image-cropper',
    name: 'Image Cropper',
    description: 'Crop images to standard aspect ratios (1:1, 4:3, 16:9) or custom bounding boxes with instant preview.',
    categorySlug: 'image',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 15,
    seoTitle: 'Free Online Image Cropper - Crop Photos & Pictures',
    seoDescription: 'Crop images easily to exact aspect ratios or custom pixel coordinates.',
    faqContent: [{ question: 'Which presets are available?', answer: '1:1 Square, 4:3 Standard, 16:9 Widescreen, and Free Crop.' }],
    relatedSlugs: ['image-resizer', 'jpg-to-png'],
  },
  {
    slug: 'webp-to-jpg',
    name: 'WebP to JPG Converter',
    description: 'Convert modern WebP images to universal JPEG format with controllable quality and clean background compositing.',
    categorySlug: 'image',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: false,
    displayOrder: 16,
    seoTitle: 'Free WebP to JPG Converter Online - Fast & High Quality',
    seoDescription: 'Convert WebP images to JPG format for universal compatibility across devices.',
    faqContent: [{ question: 'How are transparent WebP images handled?', answer: 'Transparent areas are smoothly composited over a clean white background.' }],
    relatedSlugs: ['jpg-to-webp', 'png-to-jpg'],
  },
  {
    slug: 'jpg-to-webp',
    name: 'JPG to WebP Converter',
    description: 'Convert JPG images to modern WebP format for faster web page loading and smaller file sizes.',
    categorySlug: 'image',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: false,
    displayOrder: 17,
    seoTitle: 'Free JPG to WebP Converter - Compress & Convert Images',
    seoDescription: 'Convert JPG images to WebP format to reduce file sizes by up to 30% without quality loss.',
    faqContent: [{ question: 'Why convert JPG to WebP?', answer: 'WebP provides superior compression and faster website load times.' }],
    relatedSlugs: ['webp-to-jpg', 'image-compressor'],
  },
  {
    slug: 'png-to-webp',
    name: 'PNG to WebP Converter',
    description: 'Convert PNG images to WebP format while preserving transparent alpha channels and high fidelity.',
    categorySlug: 'image',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: false,
    displayOrder: 18,
    seoTitle: 'Free PNG to WebP Converter - Transparent Alpha Preserved',
    seoDescription: 'Convert transparent PNG images to lightweight WebP files with full transparency support.',
    faqContent: [{ question: 'Is transparency preserved?', answer: 'Yes, alpha channel transparency is fully preserved in the WebP file.' }],
    relatedSlugs: ['jpg-to-webp', 'jpg-to-png'],
  },
  // PDF (MVP + Phase 27)
  {
    slug: 'pdf-compressor',
    name: 'PDF Compressor',
    description: 'Compress PDF files dramatically while preserving crisp readability and visual fidelity.',
    categorySlug: 'pdf',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 19,
    seoTitle: 'Free Online PDF Compressor - Reduce PDF Size (≤1 MB Target)',
    seoDescription: 'Compress large PDF documents down to ~1 MB with high fidelity.',
    faqContent: [{ question: 'How much size reduction can I expect?', answer: 'Depending on profile, savings range between 50% to 95%.' }],
    relatedSlugs: ['pdf-merge', 'pdf-split', 'pdf-to-jpg'],
  },
  {
    slug: 'pdf-merge',
    name: 'PDF Merge',
    description: 'Combine multiple PDF documents into a single organized, unified PDF file.',
    categorySlug: 'pdf',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 20,
    seoTitle: 'Free PDF Merge Online - Combine PDF Files Easily',
    seoDescription: 'Merge multiple PDF files into one document in seconds.',
    faqContent: [{ question: 'How many PDFs can I merge?', answer: 'Merge up to 10 PDF documents simultaneously.' }],
    relatedSlugs: ['pdf-split', 'pdf-compressor'],
  },
  {
    slug: 'pdf-split',
    name: 'PDF Split',
    description: 'Extract specific page ranges from a PDF or split documents into standalone files.',
    categorySlug: 'pdf',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 21,
    seoTitle: 'Free PDF Split Online - Split PDF by Pages or Ranges',
    seoDescription: 'Extract pages from PDF documents easily online.',
    faqContent: [{ question: 'Can I split by custom ranges?', answer: 'Yes, specify page ranges like 1-3, 5, 7.' }],
    relatedSlugs: ['pdf-page-extractor', 'pdf-merge'],
  },
  {
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG Converter',
    description: 'Convert PDF document pages to crisp high-resolution JPEG images.',
    categorySlug: 'pdf',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 22,
    seoTitle: 'Convert PDF to JPG Online - High Resolution Image Export',
    seoDescription: 'Convert PDF pages into clear JPG images. Export single pages or download a ZIP archive.',
    faqContent: [{ question: 'Can I convert all pages at once?', answer: 'Yes, all pages are rendered and bundled into a ZIP archive.' }],
    relatedSlugs: ['pdf-to-png', 'pdf-compressor'],
  },
  {
    slug: 'pdf-to-png',
    name: 'PDF to PNG Converter',
    description: 'Convert PDF document pages to crisp, high-resolution PNG images with transparent background support.',
    categorySlug: 'pdf',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 23,
    seoTitle: 'Free PDF to PNG Converter Online - High Resolution Image Export',
    seoDescription: 'Convert PDF pages into clear PNG images. Export single pages or download a ZIP archive.',
    faqContent: [{ question: 'Are multiple pages supported?', answer: 'Yes, multiple pages are rendered and bundled into a ZIP archive.' }],
    relatedSlugs: ['pdf-to-jpg', 'pdf-compressor'],
  },
  {
    slug: 'pdf-to-text',
    name: 'PDF to Text Extractor',
    description: 'Extract digital selectable text from PDF documents with clean formatting and paragraph preservation.',
    categorySlug: 'pdf',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 24,
    seoTitle: 'Free PDF to Text Extractor Online - Extract Plain Text from PDF',
    seoDescription: 'Extract selectable text from PDF documents cleanly into a UTF-8 text file.',
    faqContent: [{ question: 'Does this perform OCR on scanned pages?', answer: 'This tool extracts digital selectable text.' }],
    relatedSlugs: ['pdf-to-png', 'word-counter'],
  },
  {
    slug: 'pdf-page-extractor',
    name: 'PDF Page Extractor',
    description: 'Extract specific pages or custom page ranges (e.g. 1-3, 5, 8) into a new standalone PDF document.',
    categorySlug: 'pdf',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 25,
    seoTitle: 'Free PDF Page Extractor - Extract Pages from PDF Document',
    seoDescription: 'Select and extract specific pages from your PDF file into a new document.',
    faqContent: [{ question: 'How do I specify page ranges?', answer: 'Enter single pages or ranges separated by commas, such as "1-3, 5, 8".' }],
    relatedSlugs: ['pdf-split', 'pdf-merge'],
  },
  {
    slug: 'pdf-rotator',
    name: 'PDF Rotator',
    description: 'Rotate PDF pages permanently by 90°, 180°, or 270° with complete layout and font preservation.',
    categorySlug: 'pdf',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: false,
    displayOrder: 26,
    seoTitle: 'Free PDF Rotator Online - Rotate PDF Pages Permanently',
    seoDescription: 'Rotate individual or all pages of a PDF document by 90, 180, or 270 degrees.',
    faqContent: [{ question: 'Is rotation saved permanently?', answer: 'Yes, the downloaded PDF retains the new orientation.' }],
    relatedSlugs: ['pdf-reorder-pages', 'pdf-page-extractor'],
  },
  {
    slug: 'pdf-reorder-pages',
    name: 'PDF Reorder Pages',
    description: 'Rearrange, sort, and organize PDF pages visually to create a customized document sequence.',
    categorySlug: 'pdf',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: false,
    displayOrder: 27,
    seoTitle: 'Free PDF Page Organizer - Reorder & Sort PDF Pages',
    seoDescription: 'Easily rearrange and reorder pages in your PDF file with precision.',
    faqContent: [{ question: 'Can I remove unwanted pages?', answer: 'Yes, simply omit page numbers you do not want.' }],
    relatedSlugs: ['pdf-rotator', 'pdf-merge'],
  },
  {
    slug: 'pdf-watermark',
    name: 'PDF Watermark',
    description: 'Add custom text watermarks, confidential stamps, or copyright notices across PDF document pages.',
    categorySlug: 'pdf',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: false,
    displayOrder: 28,
    seoTitle: 'Free PDF Watermark Tool - Stamp & Watermark PDF Pages',
    seoDescription: 'Add custom diagonal or centered text watermarks with transparency to your PDF.',
    faqContent: [{ question: 'Can I adjust transparency?', answer: 'Yes, opacity and angle can be customized.' }],
    relatedSlugs: ['pdf-metadata-remover', 'pdf-compressor'],
  },
  {
    slug: 'pdf-metadata-remover',
    name: 'PDF Metadata Remover',
    description: 'Strip document metadata (Author, Title, Subject, Producer, Creation Date) from PDF files for privacy.',
    categorySlug: 'pdf',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: false,
    displayOrder: 29,
    seoTitle: 'Free PDF Metadata Remover - Sanitize Document Properties',
    seoDescription: 'Remove hidden author names, timestamps, and metadata from PDF files before sharing.',
    faqContent: [{ question: 'Which fields are removed?', answer: 'Title, Author, Subject, Keywords, Creator, and Producer.' }],
    relatedSlugs: ['pdf-watermark', 'pdf-compressor'],
  },
  // Video
  {
    slug: 'video-compressor',
    name: 'Video Compressor',
    description: 'Compress MP4 and WebM videos to reduce file size significantly for easy sharing on email and social media.',
    categorySlug: 'video',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 30,
    seoTitle: 'Free Online Video Compressor - Reduce MP4 & WebM File Size',
    seoDescription: 'Compress large videos online without visible quality loss. Fast, secure, and private.',
    faqContent: [{ question: 'What is the maximum video size?', answer: 'Upload and compress videos up to 50MB in size.' }],
    relatedSlugs: ['video-trimmer', 'mp4-to-mp3'],
  },
  {
    slug: 'mp4-to-mp3',
    name: 'MP4 to MP3 Converter',
    description: 'Extract high-fidelity audio tracks from MP4 video files into standalone MP3 format.',
    categorySlug: 'video',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 31,
    seoTitle: 'Free MP4 to MP3 Converter Online - Extract Audio from Video',
    seoDescription: 'Quickly extract crystal-clear MP3 audio tracks from any MP4 video file.',
    faqContent: [{ question: 'Can I choose audio bitrate?', answer: 'Yes, bitrates from 128 kbps to 320 kbps are supported.' }],
    relatedSlugs: ['video-compressor', 'audio-cutter'],
  },
  {
    slug: 'video-to-gif',
    name: 'Video to GIF Converter',
    description: 'Convert short video clips into lightweight, animated GIF animations with customizable FPS and dimensions.',
    categorySlug: 'video',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 32,
    seoTitle: 'Free Video to GIF Converter Online - Make Animated GIFs',
    seoDescription: 'Turn video clips into smooth animated GIFs with custom speed and resolution.',
    faqContent: [{ question: 'What is the recommended duration?', answer: 'Short clips between 2 to 10 seconds produce optimal GIFs.' }],
    relatedSlugs: ['video-trimmer', 'video-compressor'],
  },
  {
    slug: 'video-trimmer',
    name: 'Video Trimmer',
    description: 'Cut and trim video segments with millisecond precision without losing audio or video quality.',
    categorySlug: 'video',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: false,
    displayOrder: 33,
    seoTitle: 'Free Online Video Trimmer - Cut & Trim Videos Easily',
    seoDescription: 'Trim unwanted portions from the start or end of your video files online.',
    faqContent: [{ question: 'Does trimming re-encode the whole video?', answer: 'Trimming extracts the exact segment with fast rendering.' }],
    relatedSlugs: ['video-compressor', 'mp4-to-mp3'],
  },
  {
    slug: 'video-downloader',
    name: 'Video Downloader',
    description: 'Download videos directly and securely from verified HTTP/HTTPS media URLs with instant format validation.',
    categorySlug: 'video',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 34,
    seoTitle: 'Free Online Video Downloader - Download Direct MP4 & WebM URLs',
    seoDescription: 'Download and save videos directly from public web URLs safely and securely. Supports MP4, WebM, and MOV formats.',
    faqContent: [
      { question: 'What types of URLs can I download?', answer: 'You can download direct, accessible video links (such as .mp4, .webm, or .mov URLs).' },
      { question: 'Does this download from private social platforms or DRM-protected sites?', answer: 'No, this utility is built exclusively for direct, publicly accessible video URLs and does not bypass platform authentication, DRM, or access controls.' },
      { question: 'What is the maximum download file size and duration?', answer: 'We support videos up to 50MB and up to 30 minutes in duration.' },
    ],
    relatedSlugs: ['video-compressor', 'video-trimmer', 'mp4-to-mp3'],
  },
  // Audio
  {
    slug: 'audio-cutter',
    name: 'Audio Cutter',
    description: 'Cut and trim MP3 and audio tracks with precision to create ringtones, clips, and soundbites.',
    categorySlug: 'audio',
    implementationMode: 'SERVER',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 35,
    seoTitle: 'Free Online Audio Cutter - Cut & Trim MP3 Audio Tracks',
    seoDescription: 'Trim audio files and create custom MP3 sound clips with precise start and end times.',
    faqContent: [{ question: 'Which audio formats can I trim?', answer: 'We support MP3, WAV, OGG, and M4A audio files up to 30MB.' }],
    relatedSlugs: ['mp4-to-mp3', 'video-trimmer'],
  },
  // QR & Barcode
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate high-resolution QR codes for websites, text, WiFi credentials, email, and contact cards instantly.',
    categorySlug: 'qr-barcode',
    implementationMode: 'LOCAL',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 36,
    seoTitle: 'Free Online QR Code Generator - Custom QR Codes with Colors',
    seoDescription: 'Create custom QR codes for URLs, WiFi networks, and contacts with instant PNG download.',
    faqContent: [{ question: 'Do generated QR codes expire?', answer: 'No, static QR codes encode data directly and never expire.' }],
    relatedSlugs: ['qr-code-scanner', 'barcode-generator'],
  },
  {
    slug: 'qr-code-scanner',
    name: 'QR Code Scanner',
    description: 'Scan and decode QR codes instantly from image files or live camera in your browser.',
    categorySlug: 'qr-barcode',
    implementationMode: 'LOCAL',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 37,
    seoTitle: 'Free Online QR Code Scanner - Camera & Image QR Reader',
    seoDescription: 'Decode and read QR codes from images or device camera instantly without installing apps.',
    faqContent: [{ question: 'Is my scanned image uploaded to a server?', answer: 'No, all QR decoding occurs locally and privately in your browser.' }],
    relatedSlugs: ['qr-code-generator', 'barcode-generator'],
  },
  {
    slug: 'barcode-generator',
    name: 'Barcode Generator',
    description: 'Generate standard Code 128 barcodes for products, inventory, serial numbers, and labels.',
    categorySlug: 'qr-barcode',
    implementationMode: 'LOCAL',
    status: 'ACTIVE',
    isFeatured: true,
    displayOrder: 38,
    seoTitle: 'Free Online Barcode Generator - Code 128 Product & SKU Barcodes',
    seoDescription: 'Create scannable Code 128 barcodes with instant SVG and PNG download.',
    faqContent: [{ question: 'Which barcode formats are supported?', answer: 'We currently support high-density standard Code 128 barcodes.' }],
    relatedSlugs: ['qr-code-generator', 'qr-code-scanner'],
  },
];
