FROM node:22-alpine

RUN apk add --no-cache openssl wget ffmpeg

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

# Copy root monorepo manifest files
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml* .npmrc* ./
COPY apps/backend/package.json ./apps/backend/
COPY packages/shared/package.json ./packages/shared/

# Install dependencies
RUN pnpm install

# Copy source code
COPY packages/shared ./packages/shared
COPY apps/backend ./apps/backend

# Build shared package & generate Prisma client
RUN pnpm --filter @ad-utility/shared build
RUN pnpm --filter @ad-utility/backend prisma:generate

EXPOSE 4000

CMD ["pnpm", "--filter", "@ad-utility/backend", "dev"]
